### ISSUE TITLE
Question regarding configuration location

### ISSUE THREAD

**Issue by Perdjesk** [cstamas/rrf-demo#1]
Using the configuration on the maven command line works fine:
```bash
mvn -Daether.remoteRepositoryFilter.groupId=true -Daether.remoteRepositoryFilter.groupId.basedir=${PWD}/.mvn/groupIdFilters dependency:go-offline
```

However I am not able to move this configuration in a `pom.xml` and have the filters being triggered.
```xml
<project>
  [...]
  <properties>
    <aether.remoteRepositoryFilter.groupId>true</aether.remoteRepositoryFilter.groupId>
    <aether.remoteRepositoryFilter.groupId.basedir>${maven.multiModuleProjectDirectory}/.mvn/groupIdFilters</aether.remoteRepositoryFilter.groupId.basedir>
  </properties>
  [...]
</project>
```

Is there something obviously wrong or the configuration can only be place on the cli?
Thanks for any hints.

**Comment by cstamas** [comment]
See https://maven.apache.org/docs/3.9.2/release-notes.html, since Maven 3.9.2 you can have `.mvn/maven.config` file that is interpolated with values like `session.rootDirectory`, that's what you want.

Basically this file https://maven.apache.org/configure.html#mvn-maven-config-file is from 3.9.2 interpolated, plus, you have those two new values. Still, use 3.9.3 as 3.9.2 has some (windows) related bug to calculate these

**Comment by cstamas** [comment]
This makes you possible to check in RRF filter config along with sources, but not only that, same works for provided checksums etc.

**Comment by Perdjesk** [comment]
Thank you a lot for the fast answer.

> This makes you possible to check in RRF filter config along with sources,

This was exactly the use case.

Very useful demo repository, it was a good companion from the official docs https://maven.apache.org/resolver/configuration.html
